export const grenres = [
    'Đời Thường',
    'Yuri',
    'Fantasy',
    'Kinh Dị',
    'Hoạt hình Trung Quốc',
    'Drama',
    'Hài Hước',
    'Học Đường',
    'Xuyên Không - Chuyển Kiếp',
    'Harem',
    'Hành Động',
    'Ecchi',
    'Viễn Tưởng',
    'Thể Thao',
    'Super Power',
    'Siêu Nhiên',
    'Shounen',
    'Phép Thuật',
    'Phiêu Lưu',
    'Máu me',
    'Mythology',
    'Mystery',
    'Military',
];
